version: '3.7'
services:
  postgres:
    image: library/postgres:latest
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password